In [1]:
#Importing pandas to clean data
import pandas as pd
import logging as lg

In [2]:
lg.basicConfig(filename="C:/sc_LwazisileMhlambi_2026/Graduate Projects 2026 - Sales Data Processing and Business Insights System/project/data_cleaning_log.csv",
               level=lg.INFO,
               format='%(asctime)s %(levelname)s - %(message)s'
               )

In [3]:
lg.info("Loading the Uncleaned Dataset")
df = pd.read_csv(r"C:/sc_LwazisileMhlambi_2026/Graduate Projects 2026 - Sales Data Processing and Business Insights System/project/data/Messy_Sales_data.csv")
df.head()

,transaction_id,date,product,category,quantity,price,region,salesperson
0,1001,2024-01-05,Laptop,Electronics,2.0,12000,North,John
1,1002,2024-01-07,Phone,Electronics,5.0,8000,South,Mary
2,1003,2024-01-10,Tablet,Electronics,3.0,6000,East,David
3,1003,2024-01-10,Tablet,Electronics,3.0,6000,East,David
4,1004,2024-01-15,Chair,Furniture,NaN,1500,West,Sarah

In [4]:
#Viewing the different data types in the document
#The end result is that date is in string form and needs to be changed into dateformat
#The price needs to be changed into a currency (round off to 2 decimal places)
#The quantity being a float, has to change back into an integer
lg.info("Viewing the different data types in the document")
df.dtypes

transaction_id      int64
date               object
product            object
category           object
quantity          float64
price               int64
region             object
salesperson        object
dtype: object

In [5]:
#Converting date string to time
lg.info("Changing date datatype from string to datetime")
df['date'] = pd.to_datetime(df['date'], format="%Y-%m-%d")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  52 non-null     int64
 1   date            52 non-null     datetime64[ns]
 2   product         52 non-null     object
 3   category        52 non-null     object
 4   quantity        50 non-null     float64
 5   price           52 non-null     int64
 6   region          52 non-null     object
 7   salesperson     50 non-null     object
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 3.4+ KB

In [6]:
lg.info("Changing from integer to float (decimal)")
df['price'] = df['price'].astype(float)
df.head()

,transaction_id,date,product,category,quantity,price,region,salesperson
0,1001,2024-01-05,Laptop,Electronics,2.0,12000.0,North,John
1,1002,2024-01-07,Phone,Electronics,5.0,8000.0,South,Mary
2,1003,2024-01-10,Tablet,Electronics,3.0,6000.0,East,David
3,1003,2024-01-10,Tablet,Electronics,3.0,6000.0,East,David
4,1004,2024-01-15,Chair,Furniture,NaN,1500.0,West,Sarah

In [7]:
#Rechecking data types
lg.info("Rechecking data types")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  52 non-null     int64
 1   date            52 non-null     datetime64[ns]
 2   product         52 non-null     object
 3   category        52 non-null     object
 4   quantity        50 non-null     float64
 5   price           52 non-null     float64
 6   region          52 non-null     object
 7   salesperson     50 non-null     object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 3.4+ KB

In [8]:
#Looking for duplicates
lg.info("Looking for duplicates")
#We have 2 duplicates in the dataset
df.duplicated().sum()

np.int64(2)

In [9]:
#Dropping duplicated entries
lg.info("Dropping duplicated entries")
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

In [10]:
#Counting for empty rows in the dataframe
lg.info("Counting for empty rows in the dataframe")
#Result is 2 empty rows in quantity and 2 in salesperson
df.isna().sum()

transaction_id    0
date              0
product           0
category          0
quantity          2
price             0
region            0
salesperson       2
dtype: int64

In [11]:
#Showcasing specific empty rows
lg.info("Showcasing specific empty rows")
df[df.isna().any(axis=1)]

,transaction_id,date,product,category,quantity,price,region,salesperson
4,1004,2024-01-15,Chair,Furniture,NaN,1500.0,West,Sarah
10,1010,2024-02-03,Desk,Furniture,3.0,3000.0,South,NaN
45,1044,2024-04-18,Chair,Furniture,NaN,1500.0,West,Sarah
47,1046,2024-04-22,Laptop,Electronics,1.0,12000.0,South,NaN

In [ ]:
#Filling in the empty salesperson rows
lg.info("Filling in the empty salesperson rows")
df['salesperson'] = df['salesperson'].fillna('Unknown')
    #groupby('region')['salesperson'].transform(lambda x: x.fillna(x.mode()[0]))
df.isna().sum()
#df['salesperson'] = df.groupby('region')['salesperson'].transform(lambda x: x.fillna(x.mode()[0]))
#df.isna().sum()

transaction_id    0
date              0
product           0
category          0
quantity          2
price             0
region            0
salesperson       0
dtype: int64

In [ ]:
#Calculating the average number of chairs
lg.info("Calculating the average number of chairs")
avg_chairs = df[df['product'] == 'Chair']['quantity'].mean()
avg_chairs.round(0)
lg.info("Filling in the empty chair values")
#Filling in the empty chair values
df.fillna({'quantity': avg_chairs.round(0)}, inplace=True)
df.isna().sum()

In [ ]:
df

In [ ]:
#Resetting the index
lg.info("Resetting the index")
df =df.reset_index(drop=True)
df.head()

In [ ]:
#Inserting revenue column
lg.info("Inserting revenue column")
df['revenue'] = df['quantity'] * df['price']
df.head()

In [ ]:
#Adding month column
lg.info("Adding month column")
df['month'] = df['date'].dt.month_name()
df.head()

In [ ]:
df.info()

In [ ]:
lg.info("Exporting Cleaned Dataset")
lg.info("Data Cleaning Complete")
df.to_csv("C:/sc_LwazisileMhlambi_2026/Graduate Projects 2026 - Sales Data Processing and Business Insights System/project/output/clean_sales.csv", index=False)

In [ ]:
#Sales by Region
lg.info("Reading Cleaned Data for Sales by Region Aggregation")
sbr = pd.read_csv("C:/sc_LwazisileMhlambi_2026/Graduate Projects 2026 - Sales Data Processing and Business Insights System/project/output/clean_sales.csv")
sbr.tail()

In [ ]:
lg.info("Aggregating Sales by Region")
sbr = sbr.groupby('region').agg(
    total_sales_revenue = ('revenue', 'sum'),
    total_quantity_sold = ('quantity', 'sum'),
    total_number_of_orders = ('transaction_id', 'count'),
    average_sales_revenue = ('revenue', 'mean')).round(2).reset_index()

In [ ]:
sbr

In [ ]:
lg.info("Saving to sales_by_region.csv")
sbr.to_csv("C:/sc_LwazisileMhlambi_2026/Graduate Projects 2026 - Sales Data Processing and Business Insights System/project/output/sales_by_region.csv", index=False)

In [ ]:
#Sales by Product
lg.info("Reading Cleaned Data for Sales by Product Aggregation")
sbp = pd.read_csv("C:/sc_LwazisileMhlambi_2026/Graduate Projects 2026 - Sales Data Processing and Business Insights System/project/output/clean_sales.csv")
sbp.tail()

In [ ]:
lg.info("Aggregating Sales by Product")
sbp = sbp.groupby('product').agg(
    total_sales_revenue = ('revenue', 'sum'),
    total_quantity_sold = ('quantity', 'sum'),
    total_number_of_orders = ('transaction_id', 'count'),
    average_sales_revenue = ('revenue', 'mean')).round(2).reset_index()

In [ ]:
sbp

In [ ]:
lg.info("Saving to sales_by_product.csv")
sbp.to_csv("C:/sc_LwazisileMhlambi_2026/Graduate Projects 2026 - Sales Data Processing and Business Insights System/project/output/sales_by_product.csv", index=False)

In [ ]:
#Monthly Revenue
lg.info("Reading Cleaned Data for Monthly Revenue Aggregation")
mr = pd.read_csv("C:/sc_LwazisileMhlambi_2026/Graduate Projects 2026 - Sales Data Processing and Business Insights System/project/output/clean_sales.csv")
mr.tail()

In [ ]:
lg.info("Aggregating Monthly Revenue")
mr = mr.groupby('month').agg(
    total_sales_revenue = ('revenue', 'sum'),
    total_quantity_sold = ('quantity', 'sum'),
    total_number_of_orders = ('transaction_id', 'count'),
    average_sales_revenue = ('revenue', 'mean')).round(2).reset_index()

In [ ]:
mr

In [ ]:
lg.info("Saving to monthly_revenue.csv")
mr.to_csv("C:/sc_LwazisileMhlambi_2026/Graduate Projects 2026 - Sales Data Processing and Business Insights System/project/output/monthly_revenue.csv", index=False)

In [ ]:
#Sales Person Performance
lg.info("Reading Cleaned Data for Salesperson Performance Aggregation")
spp = pd.read_csv("C:/sc_LwazisileMhlambi_2026/Graduate Projects 2026 - Sales Data Processing and Business Insights System/project/output/clean_sales.csv")
spp.tail()

In [ ]:
lg.info("Aggregating Salesperson Performance")
spp = spp.groupby(['salesperson', 'product']).agg(
    total_sales_revenue = ('revenue', 'sum'),
    total_quantity_sold = ('quantity', 'sum'),
    total_number_of_orders = ('transaction_id', 'count'),
    average_sales_revenue = ('revenue', 'mean')).round(2).reset_index()

In [ ]:
spp

In [ ]:
lg.info("Saving to salesperson_performance.csv")
lg.info("Data Cleaning and Transformation Complete")
spp.to_csv("C:/sc_LwazisileMhlambi_2026/Graduate Projects 2026 - Sales Data Processing and Business Insights System/project/output/salesperson_performance.csv", index=False)