In [1]:
#Importing pandas to clean data
import pandas as pd
import logging as lg

In [2]:
lg.basicConfig(filename="C:/sc_LwazisileMhlambi_2026/Graduate Projects 2026 - Sales Data Processing and Business Insights System/project/data_cleaning_log.csv",
               level=lg.INFO,
               format='%(asctime)s %(levelname)s - %(message)s'
               )

In [3]:
lg.info("Loading the Uncleaned Dataset")
df = pd.read_csv(r"C:/sc_LwazisileMhlambi_2026/Graduate Projects 2026 - Sales Data Processing and Business Insights System/project/data/Messy_Sales_data.csv")
df.head()

,transaction_id,date,product,category,quantity,price,region,salesperson
0,1001,2024-01-05,Laptop,Electronics,2.0,12000,North,John
1,1002,2024-01-07,Phone,Electronics,5.0,8000,South,Mary
2,1003,2024-01-10,Tablet,Electronics,3.0,6000,East,David
3,1003,2024-01-10,Tablet,Electronics,3.0,6000,East,David
4,1004,2024-01-15,Chair,Furniture,NaN,1500,West,Sarah

In [4]:
#Viewing the different data types in the document
#The end result is that date is in string form and needs to be changed into dateformat
#The price needs to be changed into a currency (round off to 2 decimal places)
#The quantity being a float, has to change back into an integer
lg.info("Viewing the different data types in the document")
df.dtypes

transaction_id      int64
date                  str
product               str
category              str
quantity          float64
price               int64
region                str
salesperson           str
dtype: object

In [5]:
#Converting date string to time
lg.info("Changing date datatype from string to datetime")
df['date'] = pd.to_datetime(df['date'], format="%Y-%m-%d")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  52 non-null     int64
 1   date            52 non-null     datetime64[us]
 2   product         52 non-null     str
 3   category        52 non-null     str
 4   quantity        50 non-null     float64
 5   price           52 non-null     int64
 6   region          52 non-null     str
 7   salesperson     50 non-null     str
dtypes: datetime64[us](1), float64(1), int64(2), str(4)
memory usage: 3.4 KB

In [6]:
lg.info("Changing from integer to float (decimal)")
df['price'] = df['price'].astype(float)
df.head()

,transaction_id,date,product,category,quantity,price,region,salesperson
0,1001,2024-01-05,Laptop,Electronics,2.0,12000.0,North,John
1,1002,2024-01-07,Phone,Electronics,5.0,8000.0,South,Mary
2,1003,2024-01-10,Tablet,Electronics,3.0,6000.0,East,David
3,1003,2024-01-10,Tablet,Electronics,3.0,6000.0,East,David
4,1004,2024-01-15,Chair,Furniture,NaN,1500.0,West,Sarah

In [7]:
#Rechecking data types
lg.info("Rechecking data types")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  52 non-null     int64
 1   date            52 non-null     datetime64[us]
 2   product         52 non-null     str
 3   category        52 non-null     str
 4   quantity        50 non-null     float64
 5   price           52 non-null     float64
 6   region          52 non-null     str
 7   salesperson     50 non-null     str
dtypes: datetime64[us](1), float64(2), int64(1), str(4)
memory usage: 3.4 KB

In [8]:
#Looking for duplicates
lg.info("Looking for duplicates")
#We have 2 duplicates in the dataset
df.duplicated().sum()

np.int64(2)

In [9]:
#Dropping duplicated entries
lg.info("Dropping duplicated entries")
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

In [10]:
#Counting for empty rows in the dataframe
lg.info("Counting for empty rows in the dataframe")
#Result is 2 empty rows in quantity and 2 in salesperson
df.isna().sum()

transaction_id    0
date              0
product           0
category          0
quantity          2
price             0
region            0
salesperson       2
dtype: int64

In [11]:
#Showcasing specific empty rows
lg.info("Showcasing specific empty rows")
df[df.isna().any(axis=1)]

,transaction_id,date,product,category,quantity,price,region,salesperson
4,1004,2024-01-15,Chair,Furniture,NaN,1500.0,West,Sarah
10,1010,2024-02-03,Desk,Furniture,3.0,3000.0,South,NaN
45,1044,2024-04-18,Chair,Furniture,NaN,1500.0,West,Sarah
47,1046,2024-04-22,Laptop,Electronics,1.0,12000.0,South,NaN

In [12]:
#Filling in the empty salesperson rows
lg.info("Filling in the empty salesperson rows")
df['salesperson'] = df.groupby('region')['salesperson'].transform(lambda x: x.fillna(x.mode()[0]))
df.isna().sum()

transaction_id    0
date              0
product           0
category          0
quantity          2
price             0
region            0
salesperson       0
dtype: int64

In [13]:
#Calculating the average number of chairs
lg.info("Calculating the average number of chairs")
avg_chairs = df[df['product'] == 'Chair']['quantity'].mean()
avg_chairs.round(0)
lg.info("Filling in the empty chair values")
#Filling in the empty chair values
df.fillna({'quantity': avg_chairs.round(0)}, inplace=True)
df.isna().sum()

transaction_id    0
date              0
product           0
category          0
quantity          0
price             0
region            0
salesperson       0
dtype: int64

In [14]:
df

,transaction_id,date,product,category,quantity,price,region,salesperson
0,1001,2024-01-05,Laptop,Electronics,2.0,12000.0,North,John
1,1002,2024-01-07,Phone,Electronics,5.0,8000.0,South,Mary
2,1003,2024-01-10,Tablet,Electronics,3.0,6000.0,East,David
4,1004,2024-01-15,Chair,Furniture,5.0,1500.0,West,Sarah
5,1005,2024-01-20,Desk,Furniture,2.0,3000.0,North,John
6,1006,2024-01-22,Laptop,Electronics,1.0,12000.0,South,Mary
7,1007,2024-01-25,Phone,Electronics,6.0,8000.0,East,David
8,1008,2024-01-28,Tablet,Electronics,2.0,6000.0,West,Sarah
9,1009,2024-02-01,Chair,Furniture,5.0,1500.0,North,John
10,1010,2024-02-03,Desk,Furniture,3.0,3000.0,South,Mary
11,1011,2024-02-05,Laptop,Electronics,2.0,12000.0,East,David
12,1012,2024-02-07,Phone,Electronics,4.0,8000.0,West,Sarah
13,1013,2024-02-10,Tablet,Electronics,3.0,6000.0,North,John
14,1014,2024-02-12,Chair,Furniture,6.0,1500.0,South,Mary
15,1015,2024-02-15,Desk,Furniture,2.0,3000.0,East,David
16,1016,2024-02-18,Laptop,Electronics,1.0,12000.0,West,Sarah
17,1017,2024-02-20,Phone,Electronics,7.0,8000.0,North,John
18,1018,2024-02-22,Tablet,Electronics,2.0,6000.0,South,Mary
19,1019,2024-02-25,Chair,Furniture,4.0,1500.0,East,David
20,1020,2024-02-28,Desk,Furniture,3.0,3000.0,West,Sarah
21,1021,2024-03-02,Laptop,Electronics,2.0,12000.0,North,John
22,1022,2024-03-04,Phone,Electronics,5.0,8000.0,South,Mary
23,1023,2024-03-06,Tablet,Electronics,3.0,6000.0,East,David
24,1024,2024-03-08,Chair,Furniture,4.0,1500.0,West,Sarah
25,1025,2024-03-10,Desk,Furniture,2.0,3000.0,North,John
26,1026,2024-03-12,Laptop,Electronics,1.0,12000.0,South,Mary
27,1027,2024-03-14,Phone,Electronics,6.0,8000.0,East,David
28,1028,2024-03-16,Tablet,Electronics,2.0,6000.0,West,Sarah
29,1029,2024-03-18,Chair,Furniture,5.0,1500.0,North,John
30,1030,2024-03-20,Desk,Furniture,3.0,3000.0,South,Mary
32,1031,2024-03-22,Laptop,Electronics,2.0,12000.0,East,David
33,1032,2024-03-24,Phone,Electronics,4.0,8000.0,West,Sarah
34,1033,2024-03-26,Tablet,Electronics,3.0,6000.0,North,John
35,1034,2024-03-28,Chair,Furniture,6.0,1500.0,South,Mary
36,1035,2024-03-30,Desk,Furniture,2.0,3000.0,East,David
37,1036,2024-04-02,Laptop,Electronics,1.0,12000.0,West,Sarah
38,1037,2024-04-04,Phone,Electronics,7.0,8000.0,North,John
39,1038,2024-04-06,Tablet,Electronics,2.0,6000.0,South,Mary
40,1039,2024-04-08,Chair,Furniture,4.0,1500.0,East,David
41,1040,2024-04-10,Desk,Furniture,3.0,3000.0,West,Sarah
42,1041,2024-04-12,Laptop,Electronics,2.0,12000.0,North,John
43,1042,2024-04-14,Phone,Electronics,5.0,8000.0,South,Mary
44,1043,2024-04-16,Tablet,Electronics,3.0,6000.0,East,David
45,1044,2024-04-18,Chair,Furniture,5.0,1500.0,West,Sarah
46,1045,2024-04-20,Desk,Furniture,2.0,3000.0,North,John
47,1046,2024-04-22,Laptop,Electronics,1.0,12000.0,South,Mary
48,1047,2024-04-24,Phone,Electronics,6.0,8000.0,East,David
49,1048,2024-04-26,Tablet,Electronics,2.0,6000.0,West,Sarah
50,1049,2024-04-28,Chair,Furniture,5.0,1500.0,North,John
51,1050,2024-04-30,Desk,Furniture,3.0,3000.0,South,Mary

In [15]:
#Resetting the index
lg.info("Resetting the index")
df =df.reset_index(drop=True)
df.head()

,transaction_id,date,product,category,quantity,price,region,salesperson
0,1001,2024-01-05,Laptop,Electronics,2.0,12000.0,North,John
1,1002,2024-01-07,Phone,Electronics,5.0,8000.0,South,Mary
2,1003,2024-01-10,Tablet,Electronics,3.0,6000.0,East,David
3,1004,2024-01-15,Chair,Furniture,5.0,1500.0,West,Sarah
4,1005,2024-01-20,Desk,Furniture,2.0,3000.0,North,John

In [16]:
#Inserting revenue column
lg.info("Inserting revenue column")
df['revenue'] = df['quantity'] * df['price']
df.head()

,transaction_id,date,product,category,quantity,price,region,salesperson,revenue
0,1001,2024-01-05,Laptop,Electronics,2.0,12000.0,North,John,24000.0
1,1002,2024-01-07,Phone,Electronics,5.0,8000.0,South,Mary,40000.0
2,1003,2024-01-10,Tablet,Electronics,3.0,6000.0,East,David,18000.0
3,1004,2024-01-15,Chair,Furniture,5.0,1500.0,West,Sarah,7500.0
4,1005,2024-01-20,Desk,Furniture,2.0,3000.0,North,John,6000.0

In [17]:
#Adding month column
lg.info("Adding month column")
df['month'] = df['date'].dt.month_name()
df.head()

,transaction_id,date,product,category,quantity,price,region,salesperson,revenue,month
0,1001,2024-01-05,Laptop,Electronics,2.0,12000.0,North,John,24000.0,January
1,1002,2024-01-07,Phone,Electronics,5.0,8000.0,South,Mary,40000.0,January
2,1003,2024-01-10,Tablet,Electronics,3.0,6000.0,East,David,18000.0,January
3,1004,2024-01-15,Chair,Furniture,5.0,1500.0,West,Sarah,7500.0,January
4,1005,2024-01-20,Desk,Furniture,2.0,3000.0,North,John,6000.0,January

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  50 non-null     int64
 1   date            50 non-null     datetime64[us]
 2   product         50 non-null     str
 3   category        50 non-null     str
 4   quantity        50 non-null     float64
 5   price           50 non-null     float64
 6   region          50 non-null     str
 7   salesperson     50 non-null     str
 8   revenue         50 non-null     float64
 9   month           50 non-null     str
dtypes: datetime64[us](1), float64(3), int64(1), str(5)
memory usage: 4.0 KB

In [19]:
lg.info("Exporting Cleaned Dataset")
lg.info("Data Cleaning Complete")
df.to_csv("C:/sc_LwazisileMhlambi_2026/Graduate Projects 2026 - Sales Data Processing and Business Insights System/project/output/clean_sales.csv", index=False)

In [20]:
#Sales by Region
lg.info("Reading Cleaned Data for Sales by Region Aggregation")
sbr = pd.read_csv("C:/sc_LwazisileMhlambi_2026/Graduate Projects 2026 - Sales Data Processing and Business Insights System/project/output/clean_sales.csv")
sbr.tail()

,transaction_id,date,product,category,quantity,price,region,salesperson,revenue,month
45,1046,2024-04-22,Laptop,Electronics,1.0,12000.0,South,Mary,12000.0,April
46,1047,2024-04-24,Phone,Electronics,6.0,8000.0,East,David,48000.0,April
47,1048,2024-04-26,Tablet,Electronics,2.0,6000.0,West,Sarah,12000.0,April
48,1049,2024-04-28,Chair,Furniture,5.0,1500.0,North,John,7500.0,April
49,1050,2024-04-30,Desk,Furniture,3.0,3000.0,South,Mary,9000.0,April

In [21]:
lg.info("Aggregating Sales by Region")
sbr = sbr.groupby('region').agg(
    total_sales_revenue = ('revenue', 'sum'),
    total_quantity_sold = ('quantity', 'sum'),
    total_number_of_orders = ('transaction_id', 'count'),
    average_sales_revenue = ('revenue', 'mean')).round(2).reset_index()

In [22]:
sbr

,region,total_sales_revenue,total_quantity_sold,total_number_of_orders,average_sales_revenue
0,East,270000.0,43.0,12,22500.00
1,North,260500.0,47.0,13,20038.46
2,South,225000.0,43.0,13,17307.69
3,West,163000.0,36.0,12,13583.33

In [23]:
lg.info("Saving to sales_by_region.csv")
sbr.to_csv("C:/sc_LwazisileMhlambi_2026/Graduate Projects 2026 - Sales Data Processing and Business Insights System/project/output/sales_by_region.csv", index=False)

In [24]:
#Sales by Product
lg.info("Reading Cleaned Data for Sales by Product Aggregation")
sbp = pd.read_csv("C:/sc_LwazisileMhlambi_2026/Graduate Projects 2026 - Sales Data Processing and Business Insights System/project/output/clean_sales.csv")
sbp.tail()

,transaction_id,date,product,category,quantity,price,region,salesperson,revenue,month
45,1046,2024-04-22,Laptop,Electronics,1.0,12000.0,South,Mary,12000.0,April
46,1047,2024-04-24,Phone,Electronics,6.0,8000.0,East,David,48000.0,April
47,1048,2024-04-26,Tablet,Electronics,2.0,6000.0,West,Sarah,12000.0,April
48,1049,2024-04-28,Chair,Furniture,5.0,1500.0,North,John,7500.0,April
49,1050,2024-04-30,Desk,Furniture,3.0,3000.0,South,Mary,9000.0,April

In [25]:
lg.info("Aggregating Sales by Product")
sbp = sbp.groupby('product').agg(
    total_sales_revenue = ('revenue', 'sum'),
    total_quantity_sold = ('quantity', 'sum'),
    total_number_of_orders = ('transaction_id', 'count'),
    average_sales_revenue = ('revenue', 'mean')).round(2).reset_index()

In [26]:
sbp

,product,total_sales_revenue,total_quantity_sold,total_number_of_orders,average_sales_revenue
0,Chair,73500.0,49.0,10,7350.0
1,Desk,75000.0,25.0,10,7500.0
2,Laptop,180000.0,15.0,10,18000.0
3,Phone,440000.0,55.0,10,44000.0
4,Tablet,150000.0,25.0,10,15000.0

In [27]:
lg.info("Saving to sales_by_product.csv")
sbp.to_csv("C:/sc_LwazisileMhlambi_2026/Graduate Projects 2026 - Sales Data Processing and Business Insights System/project/output/sales_by_product.csv", index=False)

In [28]:
#Monthly Revenue
lg.info("Reading Cleaned Data for Monthly Revenue Aggregation")
mr = pd.read_csv("C:/sc_LwazisileMhlambi_2026/Graduate Projects 2026 - Sales Data Processing and Business Insights System/project/output/clean_sales.csv")
mr.tail()

,transaction_id,date,product,category,quantity,price,region,salesperson,revenue,month
45,1046,2024-04-22,Laptop,Electronics,1.0,12000.0,South,Mary,12000.0,April
46,1047,2024-04-24,Phone,Electronics,6.0,8000.0,East,David,48000.0,April
47,1048,2024-04-26,Tablet,Electronics,2.0,6000.0,West,Sarah,12000.0,April
48,1049,2024-04-28,Chair,Furniture,5.0,1500.0,North,John,7500.0,April
49,1050,2024-04-30,Desk,Furniture,3.0,3000.0,South,Mary,9000.0,April

In [29]:
lg.info("Aggregating Monthly Revenue")
mr = mr.groupby('month').agg(
    total_sales_revenue = ('revenue', 'sum'),
    total_quantity_sold = ('quantity', 'sum'),
    total_number_of_orders = ('transaction_id', 'count'),
    average_sales_revenue = ('revenue', 'mean')).round(2).reset_index()

In [30]:
mr

,month,total_sales_revenue,total_quantity_sold,total_number_of_orders,average_sales_revenue
0,April,279000.0,51.0,15,18600.00
1,February,200500.0,42.0,12,16708.33
2,January,167500.0,26.0,8,20937.50
3,March,271500.0,50.0,15,18100.00

In [31]:
lg.info("Saving to monthly_revenue.csv")
mr.to_csv("C:/sc_LwazisileMhlambi_2026/Graduate Projects 2026 - Sales Data Processing and Business Insights System/project/output/monthly_revenue.csv", index=False)

In [32]:
#Sales Person Performance
lg.info("Reading Cleaned Data for Salesperson Performance Aggregation")
spp = pd.read_csv("C:/sc_LwazisileMhlambi_2026/Graduate Projects 2026 - Sales Data Processing and Business Insights System/project/output/clean_sales.csv")
spp.tail()

,transaction_id,date,product,category,quantity,price,region,salesperson,revenue,month
45,1046,2024-04-22,Laptop,Electronics,1.0,12000.0,South,Mary,12000.0,April
46,1047,2024-04-24,Phone,Electronics,6.0,8000.0,East,David,48000.0,April
47,1048,2024-04-26,Tablet,Electronics,2.0,6000.0,West,Sarah,12000.0,April
48,1049,2024-04-28,Chair,Furniture,5.0,1500.0,North,John,7500.0,April
49,1050,2024-04-30,Desk,Furniture,3.0,3000.0,South,Mary,9000.0,April

In [33]:
lg.info("Aggregating Salesperson Performance")
spp = spp.groupby(['salesperson', 'product']).agg(
    total_sales_revenue = ('revenue', 'sum'),
    total_quantity_sold = ('quantity', 'sum'),
    total_number_of_orders = ('transaction_id', 'count'),
    average_sales_revenue = ('revenue', 'mean')).round(2).reset_index()

In [34]:
spp

,salesperson,product,total_sales_revenue,total_quantity_sold,total_number_of_orders,average_sales_revenue
0,David,Chair,12000.0,8.0,2,6000.0
1,David,Desk,12000.0,4.0,2,6000.0
2,David,Laptop,48000.0,4.0,2,24000.0
3,David,Phone,144000.0,18.0,3,48000.0
4,David,Tablet,54000.0,9.0,3,18000.0
5,John,Chair,22500.0,15.0,3,7500.0
6,John,Desk,18000.0,6.0,3,6000.0
7,John,Laptop,72000.0,6.0,3,24000.0
8,John,Phone,112000.0,14.0,2,56000.0
9,John,Tablet,36000.0,6.0,2,18000.0
10,Mary,Chair,18000.0,12.0,2,9000.0
11,Mary,Desk,27000.0,9.0,3,9000.0
12,Mary,Laptop,36000.0,3.0,3,12000.0
13,Mary,Phone,120000.0,15.0,3,40000.0
14,Mary,Tablet,24000.0,4.0,2,12000.0
15,Sarah,Chair,21000.0,14.0,3,7000.0
16,Sarah,Desk,18000.0,6.0,2,9000.0
17,Sarah,Laptop,24000.0,2.0,2,12000.0
18,Sarah,Phone,64000.0,8.0,2,32000.0
19,Sarah,Tablet,36000.0,6.0,3,12000.0

In [35]:
lg.info("Saving to salesperson_performance.csv")
lg.info("Data Cleaning and Transformation Complete")
spp.to_csv("C:/sc_LwazisileMhlambi_2026/Graduate Projects 2026 - Sales Data Processing and Business Insights System/project/output/salesperson_performance.csv", index=False)