In [1]:
import numpy as np
import pandas as pd

In [2]:
from numpy.random import randn

In [3]:
np.random.seed(101)

In [5]:
df = pd.DataFrame(randn(5,4),['A','B','C','D','E'], ['W','X','Y','Z'])
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [7]:
#Conditional selection
booldf = df > 0

In [8]:
booldf

       W      X      Y      Z
A   True   True  False  False
B  False   True   True   True
C   True   True   True   True
D  False  False  False   True
E  False   True   True   True

In [9]:
df[booldf]

          W         X         Y         Z
A  0.302665  1.693723       NaN       NaN
B       NaN  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D       NaN       NaN       NaN  0.484752
E       NaN  1.901755  0.238127  1.996652

In [10]:
df['W']>0

A     True
B    False
C     True
D    False
E    False
Name: W, dtype: bool

In [11]:
df[df['W']>0]

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646

In [13]:
resultdf = df[df['W']>0]

In [15]:
resultdf['X']

A    1.693723
C    0.072960
Name: X, dtype: float64

In [16]:
#Can write it all in one
df[df['W']>0]['X']

A    1.693723
C    0.072960
Name: X, dtype: float64

In [21]:
boolser = df['W']> 0
result = df[boolser]
mycols = ['Y', 'X']
result[mycols]

          Y         X
A -1.706086  1.693723
C  0.638787  0.072960

In [20]:
result

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646

In [ ]:
df[(df['W']>0) & (df['X']>1)]

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646
E -0.116773  1.901755  0.238127  1.996652

In [ ]:
df[(df['W']>0) | (df['X']>1)]

In [29]:
#Resetting or setting an index

In [30]:
df.reset_index()

  index         W         X         Y         Z
0     A  0.302665  1.693723 -1.706086 -1.159119
1     B -0.134841  0.390528  0.166905  0.184502
2     C  0.807706  0.072960  0.638787  0.329646
3     D -0.497104 -0.754070 -0.943406  0.484752
4     E -0.116773  1.901755  0.238127  1.996652

In [32]:
newind = 'CA NY WY OR CO'.split()
newind

['CA', 'NY', 'WY', 'OR', 'CO']

In [33]:
df['Staes'] = newind

In [36]:
df

          W         X         Y         Z Staes
A  0.302665  1.693723 -1.706086 -1.159119    CA
B -0.134841  0.390528  0.166905  0.184502    NY
C  0.807706  0.072960  0.638787  0.329646    WY
D -0.497104 -0.754070 -0.943406  0.484752    OR
E -0.116773  1.901755  0.238127  1.996652    CO

In [37]:
df.set_index('Staes')

              W         X         Y         Z
Staes
CA     0.302665  1.693723 -1.706086 -1.159119
NY    -0.134841  0.390528  0.166905  0.184502
WY     0.807706  0.072960  0.638787  0.329646
OR    -0.497104 -0.754070 -0.943406  0.484752
CO    -0.116773  1.901755  0.238127  1.996652