In [8]:
import numpy as np
import pandas as pd
from numpy.random import randn

In [9]:
#Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside, inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [10]:
outside

['G1', 'G1', 'G1', 'G2', 'G2', 'G2']

In [11]:
inside

[1, 2, 3, 1, 2, 3]

In [12]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [14]:
df = pd.DataFrame(randn(6,2),hier_index,['A','B'])

In [ ]:
#Multi-level index
df

             A         B
G1 1  0.044973  0.567928
   2  0.729445  0.473468
   3  1.280086  0.454198
G2 1 -1.195770  0.278833
   2  0.347178 -1.953079
   3 -1.606220 -0.757105

In [ ]:
#Calling from multi-level index
df.loc['G1'].loc[1]

A    0.044973
B    0.567928
Name: 1, dtype: float64

In [ ]:
#Labelling index columns
df.index.names = ['Groups', 'Num']

In [19]:
df

                   A         B
Groups Num
G1     1    0.044973  0.567928
       2    0.729445  0.473468
       3    1.280086  0.454198
G2     1   -1.195770  0.278833
       2    0.347178 -1.953079
       3   -1.606220 -0.757105

In [23]:
df.loc['G2'].loc[2].loc['B']

np.float64(-1.9530788375530999)

In [24]:
#Returns Cross Section from a Data frame
df.xs

<bound method NDFrame.xs of                    A         B
Groups Num
G1     1    0.044973  0.567928
       2    0.729445  0.473468
       3    1.280086  0.454198
G2     1   -1.195770  0.278833
       2    0.347178 -1.953079
       3   -1.606220 -0.757105>

In [25]:
df.xs('G1')

            A         B
Num
1    0.044973  0.567928
2    0.729445  0.473468
3    1.280086  0.454198

In [ ]:
#Can specify which level of an index you want
df.xs(1,level='Num')

               A         B
Groups
G1      0.044973  0.567928
G2     -1.195770  0.278833